// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVDtcd8PnGLk2PmFOgYo3124-abOZsq3E',
    appId: '1:490476729637:web:a1b44056df81e91d0456cc',
    messagingSenderId: '490476729637',
    projectId: 'case-study-29aff',
    authDomain: 'case-study-29aff.firebaseapp.com',
    storageBucket: 'case-study-29aff.appspot.com',
    measurementId: 'G-B9XJSF2XHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcj7BM18IyM5wkWlqhxw3kQJAXtodLpJM',
    appId: '1:490476729637:android:ef44928dd598e7250456cc',
    messagingSenderId: '490476729637',
    projectId: 'case-study-29aff',
    storageBucket: 'case-study-29aff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9zPviieDAGzBpan4V3bYxbNNYDbmXiVY',
    appId: '1:490476729637:ios:6b90a1d2b63967700456cc',
    messagingSenderId: '490476729637',
    projectId: 'case-study-29aff',
    storageBucket: 'case-study-29aff.appspot.com',
    iosBundleId: 'com.example.caseStudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9zPviieDAGzBpan4V3bYxbNNYDbmXiVY',
    appId: '1:490476729637:ios:7c098916ad36e4f90456cc',
    messagingSenderId: '490476729637',
    projectId: 'case-study-29aff',
    storageBucket: 'case-study-29aff.appspot.com',
    iosBundleId: 'com.example.caseStudy.RunnerTests',
  );
}
